spring.application.name=tecnologia
# Configuración de PostgreSQL (puede ser otra bd)
spring.r2dbc.url=r2dbc:mysql://localhost:3306/tech
spring.r2dbc.username=root
spring.r2dbc.password=admin

# Ejecutar scripts de inicialización
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
