spring.application.name=tecnologia

spring.r2dbc.url=r2dbc:mysql://localhost:3306/tech
spring.r2dbc.username=root
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
